# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 89fd81227cfe8284f21bc717882d8770806f499148d2d40ee1f07e646d8e909225d290e1bd483cacd8ee8c378d46a5529bb68074344ade00c9b9e2825b0e5e66

test:
  secret_key_base: 74e1b5c151dd464789e8810a22b4976e74dae75684ccaab26e30363d6b591d4563682bb465b5a21eb5b131769ca6b43e8bc632ba9140efcf1f936705a9bf386e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
